### ISSUE TITLE
ip涉及敏感信息，麻烦删除一下

### ISSUE THREAD

**Issue by frhui** [zhaojunliing/markDownDoc#1]
https://github.com/zhaojunliing/markDownDoc/blob/81137b5f3c08ccd2c81d350277986ad3d031d5ff/%E5%85%B6%E4%BB%96/Dubbo%E5%BC%82%E5%B8%B8%EF%BC%9Aforbid%20consumer.md?plain=1#L16

**Comment by zhaojunliing** [comment]
都是私网地址，不是互联网。这边也处理下
